# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  run-openmpi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openmpi-bin
        python -m pip install --upgrade pip
        pip install .
        pip install nbformat mpi4py
    - name: Run the OSU bandwidth example
      run: |
        mpirun --version
        ipython examples/osu_bw_mpi4py.ipynb

  run-local:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install nbformat
    - name: Run a non-MPI cluster example
      run: |
        ipython examples/non-mpi_cluster.ipynb
